### ISSUE TITLE
Loads active players but nothing else

### ISSUE THREAD

**Issue by lukemattle** [gloaysa/whatsplaying#9]
When I load WhatsPlaying and input my token, it can load the active players but nothing else (album art, track, lyrics, etc...)
On Firefox, I get lots of CORS errors:
![image](https://github.com/user-attachments/assets/f9a066e2-cda8-469c-96f3-38ca51dfce39)
On Chrome, I get lots of ERR_CONNECTION_REFUSED errors
![image](https://github.com/user-attachments/assets/818d5a60-d192-4a41-90da-2aeb59d65b5f)

I am running it on Unraid v6.12.6 with Docker version 20.10.24, build 297e128
I have Remote Control enabled in Plexamp on all devices

Here is my compose file:
```
version:` '3.8'
services:
  whatsplaying:
    container_name: whatsplaying
    restart: unless-stopped
    image: ghcr.io/gloaysa/whatsplaying:latest
    environment:
      - PORT=5000 # default is 5000
    ports:
      - '5000:5000'
```
